### ISSUE TITLE
jrc download samples does not work

### ISSUE THREAD

**Issue by yurikadoi** [JaneliaSciComp/JRCLUST#58]
I get this error

>>jrc donwload sample
Running 'C:\JRCLUST_uchida\JRCLUST-3.2.5\jrc3.m'
>>Must provide .prm file

**Comment by aliddell** [comment]
Hi. Looks like you've got a typo in your command there, which is why it's asking for a .prm file. This function has been deprecated because the original Dropbox links for sample.bin and sample.meta are broken.

However, we're hosting those files on Google Drive:
https://drive.google.com/file/d/1-ZCiWHcrs_w5sasxbvGzsupDEueCwOGV/view?usp=sharing
https://drive.google.com/file/d/1-aDLNgTa2UPKVpxe0eHQajKSrm_FkEZ6/view?usp=sharing

Don't hesitate to ask if you need more help.

**Comment by yurikadoi** [comment]
thanks!
